version: '3'
services:
  vehicles-api:
    image: jflc/vehicles-api:latest
    container_name: vehicles-api-container
    depends_on:
      - vehicles-db
    links:
      - vehicles-db
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://vehicles-db:27017
  vehicles-db:
    image: mongo:4.0
    container_name: vehicles-db-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: vehicles-api
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro